version: "3.8"
services:

  zrd-postgres:
    image: "postgres:14"
    container_name: "rzd-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rzd-postgres
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  rzd-service:
    depends_on:
      - zrd-postgres
    build: /
    container_name: "rzd-service"
    ports:
      - 8085:8085
    environment:
      - POSTGRES_HOST=zrd-postgres
      - POSTGRES_DB=rzd-postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    restart: on-failure