version: "3.8"
services:

  zrd-postgres:
    image: "postgres:14"
    container_name: "rzd-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rzd-postgres
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

#  task-service:
#    depends_on:
#      - juniorhub-postgres
#    build: /
#    container_name: "task-service"
#    ports:
#      - 9003:9003
#      - 8003:8003
#    environment:
#      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8003
#      - SPRING_R2DBC_URL=r2dbc:postgresql://juniorhub-postgres:5432/juniorhubdb_task
#      - SPRING_FLYWAY_URL=jdbc:postgresql://juniorhub-postgres:5432/juniorhubdb_task
#    restart: on-failure