create table directory_of_cargo_nomenclatures
(
    id              int4 generated by default as identity,
    code            varchar(255),
    shipping_name   varchar(255),
    nomenclature_id int4,
    primary key (id)
);

create table full_scale
(
    id                 int4 generated by default as identity,
    composition_number int4,
    primary key (id)
);

create table scale
(
    id            int4 generated by default as identity,
    cargo_weight  numeric(19, 2),
    serial_number int4 unique,
    wagon_weight  numeric(19, 2),
    wagon_number  int4,
    scale_id      int4,
    primary key (id)
);

create table station_model
(
    id           int4 generated by default as identity,
    station_name varchar(255),
    primary key (id)
);

create table station_entity_number
(
    station_entity_id int4 not null,
    number            int4
);

create table wagon_passport
(
    id            int4 generated by default as identity,
    load_capacity int4,
    number        int4,
    tare_weight   int4,
    type          varchar(255),
    primary key (id)
);

alter table if exists directory_of_cargo_nomenclatures
    add constraint UK_ebq73euxlhrc77sm8oj9ss77t unique (code);

alter table if exists directory_of_cargo_nomenclatures
    add constraint UK_c4re2lej8od96witk62ianbjt unique (shipping_name);

alter table if exists full_scale
    add constraint UK_gs9ctyrdr1ltwau5362nfb66k unique (composition_number);

alter table if exists station_model
    add constraint UK_4wymobyha9jcye1d0xkyb25mc unique (station_name);

alter table if exists wagon_passport
    add constraint UK_3b32orqd2ocyvshbkak79y66x unique (number);

alter table if exists directory_of_cargo_nomenclatures
    add constraint FK7t66fbfwa0u9ti2axtv2895y3 foreign key (nomenclature_id) references scale;

alter table if exists scale
    add constraint FKj075kbiqyo6u5ehaqk0ltkmpc foreign key (wagon_number) references wagon_passport;

alter table if exists scale
    add constraint FKa7e26610xudyrjycduwvrwbc3 foreign key (scale_id) references full_scale;

alter table if exists station_entity_number
    add constraint FKnsy1n6ypcbkkuvn4vaea3i0ek foreign key (station_entity_id) references station_model;