create table directory_of_cargo_nomenclatures
(
    id            int4 generated by default as identity,
    code          varchar(255) unique,
    shipping_name varchar(255) unique,
    primary key (id)
);
create table directory_of_cargo_nomenclatures_scale
(
    nomenclatures_id int4 not null,
    scale_id         int4 not null
);
create table full_scale
(
    id int4 generated by default as identity,
    primary key (id)
);
create table full_scale_scales
(
    full_scale_id int4 not null,
    scales_id     int4 not null
);
create table scale
(
    id            int4 generated by default as identity,
    cargo_weight  numeric(19, 2),
    serial_number int4,
    wagon_weight  numeric(19, 2),
    wagon_number  int4,
    primary key (id)
);
create table station_model
(
    id           int4 generated by default as identity,
    station_name varchar(255) unique,
    primary key (id)
);
create table station_entity_number
(
    station_entity_id int4 not null,
    number            int4
);
create table wagon_passport
(
    id            int4 generated by default as identity,
    load_capacity int4,
    number        int4 not null unique ,
    tare_weight   int4,
    type          varchar(255),
    primary key (id)
);
alter table if exists full_scale_scales
    drop constraint if exists UK_2uu3gmepqf6qc62xl4rxrgvl1;

alter table if exists full_scale_scales
    add constraint UK_2uu3gmepqf6qc62xl4rxrgvl1 unique (scales_id);
alter table if exists directory_of_cargo_nomenclatures_scale
    add constraint FKi2opfd8m4jksk1p7cx0k7pacw foreign key (scale_id) references scale;
alter table if exists directory_of_cargo_nomenclatures_scale
    add constraint FK2s1wufwiottng9bnwvvf2djxr foreign key (nomenclatures_id) references directory_of_cargo_nomenclatures;
alter table if exists full_scale_scales
    add constraint FKbic0g3mhnny6qht6gy00lbqcc foreign key (scales_id) references scale;
alter table if exists full_scale_scales
    add constraint FKk2f4jd09n2pb4mkdkoij27l1n foreign key (full_scale_id) references full_scale;
alter table if exists scale
    add constraint FKj075kbiqyo6u5ehaqk0ltkmpc foreign key (wagon_number) references wagon_passport;
alter table if exists station_entity_number
    add constraint FKnsy1n6ypcbkkuvn4vaea3i0ek foreign key (station_entity_id) references station_model;
